spring:
  datasource:
    url: jdbc:mysql://localhost:3307/api-logos-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: t1i1WYjxVkF+JJoeaw8Rh+yfS4AHqkiGHaY/DP5QAsE=